config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      post 'device_api/create'
    end
  end
  devise_for :users
  root 'pages#index'

  resources :admin_panel, only: [:index]
  get 'admin/users_panel', to: 'admin_panel#show_users_panel', as: 'show_users_panel'
  get 'admin/devices_panel', to: 'admin_panel#show_devices_panel', as: 'show_devices_panel'
  post 'admin/generate_new_user_token/:id', to: 'admin_panel#generate_new_token', as: 'gen_new_token'

  resources :user_panel, only: [:index]

  resources :devices
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
class Device < ApplicationRecord
    belongs_to :user
    has_many :ratings
end

app/models/rating.rb
class Rating < ApplicationRecord
    belongs_to :device
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :user_roles
    has_many :users, through: :user_roles
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_roles
  has_many :roles, through: :user_roles
  has_many :devices
end

app/models/user_role.rb
class UserRole < ApplicationRecord
    belongs_to :user
    belongs_to :role
end

app/controllers/admin_panel_controller.rb
class AdminPanelController < ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_admin

    def index
    end

    def show_users_panel
        @users = User.all
    end

    def generate_new_token
        @user = User.find(params[:id])
        @user.token = SecureRandom.hex
        @user.save

        respond_to do |format|
            format.js
        end
    end

    def show_devices_panel
        redirect_to devices_path
    end
end

app/controllers/api/v1/device_api_controller.rb
class Api::V1::DeviceApiController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :find_user

  def create
    all_devices = @current_user.devices
    devices_inactive = @current_user.devices.where.not(uuid: params[:uuids])
    ratings_to_create = []
    
    all_devices.each do |device|
      device_inactive = devices_inactive.select { |device_inactive| device_inactive.uuid == device.uuid }.blank?
      power_rating = 0
      if device_inactive
        power_rating = device.power_rating
      end
      
      rating = {
        device_id: device.id,
        power_consumption: power_rating,
        is_online: device_inactive
      }

      ratings_to_create.push(rating)
    end

    ActiveRecord::Base.transaction do
      if Rating.create! ratings_to_create
        latest_ratings = Device.all.includes(:ratings).map { |device| device.ratings.last }
        latest_ratings = latest_ratings.reject { |rating| rating.blank? }
        ActionCable.server.broadcast 'admin_room_channel', latest_ratings: Device.all.includes(:ratings).map { |device| device.ratings.last }
        render json: { message: 'Ok' }
      end
    end
  end

  private

  def set_params
    params.require(:rating).permit()
  end

  def find_user
    @current_user = User.find_by_token(params[:user_token])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_user_admin?
        return current_user.roles.select { |role| role.name == 'admin' }.present?
    end

    def authenticate_admin
        if user_signed_in?
            if !current_user_admin?
                redirect_to user_panel_index_path
            end
        end
    end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_admin, only: [:index]
    before_action :is_admin?
    before_action :find_device, only: [:show, :edit, :update, :destroy]

    def index
        @devices = Device.all.includes(:ratings)
        @last_ratings = Device.all.includes(:ratings).map { |device| device.ratings.last }
        @last_ratings = @last_ratings.reject { |element| element.blank? }
    end

    def new
        @device = Device.new
        respond_to do |format|
            format.js
        end
    end

    def create
        @device = Device.new(set_params)
        @device.uuid = SecureRandom.hex
        if @device.save
            ActionCable.server.broadcast 'admin_room_channel', latest_ratings: Device.all.includes(:ratings).map { |device| device.ratings.last }
            respond_to do |format|
                format.js
            end
        end 
    end

    def show
        @device_ratings = Rating.where(device: @device)
        respond_to do |format|
            format.js
        end
    end

    def edit
        respond_to do |format|
            format.js
        end
    end

    def update
        if @device.update(set_params)
            respond_to do |format|
                format.js
            end
        end 
    end

    def destroy
        if @device.destroy
            respond_to do |format|
                format.js
            end
        end
    end

    private

    def set_params
        params.require(:device).permit(:name, :user_id, :power_rating)
    end

    def find_device
        @device = Device.find(params[:id])
    end

    def is_admin?
        @is_admin = current_user_admin?
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    if user_signed_in?
      if current_user_admin?
        redirect_to admin_panel_index_path
      else
        redirect_to user_panel_index_path
      end
    end
  end

end

app/controllers/user_panel_controller.rb
class UserPanelController < ApplicationController
end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
end

app/helpers/api/v1/device_api_helper.rb
module Api::V1::DeviceApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_panel_helper.rb
module UserPanelHelper
end

app/views/admin_panel/generate_new_token.js.erb
$('#user-token-<%= @user.id %>').replaceWith('<td id="user-token-<%= @user.id %>"><%= @user.token %></td>')

app/views/admin_panel/index.html.erb
Graphs

app/views/admin_panel/show_users_panel.html.erb
<% if @users.present? %>
    <table class="table">
        <thead class="thead-dark">
            <tr>
            <th scope="col">#</th>
            <th scope="col">email</th>
            <th scope="col">token</th>
            <th scope="col">Created At</th>
            <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @users.each do |user| %>
                <tr>
                    <th scope="row"><%= user.id %></th>
                    <td><%= user.email %></td>
                    <td id="user-token-<%= user.id %>"><%= user.token %></td>
                    <td><%= user.created_at %></td>
                    <td>
                        <%= link_to "New Token", gen_new_token_path(user), method: :post, remote: true %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% else %>
    <div class="alert alert-primary" role="alert">
        No Data Found!
    </div>
<% end %>

app/views/devices/_device.html.erb
<div class="card bg-light mb-3">
  <div class="card-header"><%= device.name %> <button class="close" onclick="closeChart()">&#10005;</button></div>
  <div class="card-body">
    <h5 class="card-title"><%= device.uuid %></h5>
  </div>
</div>

<script>
    // var canvas = document.getElementById("device-chart");
    // var ctx = canvas.getContext('2d');

    // // Global Options:
    // Chart.defaults.global.defaultFontColor = 'black';
    // Chart.defaults.global.defaultFontSize = 16;

    // var data = {
    //     labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    //     datasets: [{
    //             label: "Stock A",
    //             fill: false,
    //             lineTension: 0.1,
    //             backgroundColor: "rgba(225,0,0,0.4)",
    //             borderColor: "red", // The main line color
    //             borderCapStyle: 'square',
    //             borderDash: [], // try [5, 15] for instance
    //             borderDashOffset: 0.0,
    //             borderJoinStyle: 'miter',
    //             pointBorderColor: "black",
    //             pointBackgroundColor: "white",
    //             pointBorderWidth: 1,
    //             pointHoverRadius: 8,
    //             pointHoverBackgroundColor: "yellow",
    //             pointHoverBorderColor: "brown",
    //             pointHoverBorderWidth: 2,
    //             pointRadius: 4,
    //             pointHitRadius: 10,
    //             // notice the gap in the data and the spanGaps: true
    //             data: [65, 59, 80, 81, 56, 55, 40, ,60,55,30,78],
    //             spanGaps: true,
    //         }, {
    //             label: "Stock B",
    //             fill: true,
    //             lineTension: 0.1,
    //             backgroundColor: "rgba(167,105,0,0.4)",
    //             borderColor: "rgb(167, 105, 0)",
    //             borderCapStyle: 'butt',
    //             borderDash: [],
    //             borderDashOffset: 0.0,
    //             borderJoinStyle: 'miter',
    //             pointBorderColor: "white",
    //             pointBackgroundColor: "black",
    //             pointBorderWidth: 1,
    //             pointHoverRadius: 8,
    //             pointHoverBackgroundColor: "brown",
    //             pointHoverBorderColor: "yellow",
    //             pointHoverBorderWidth: 2,
    //             pointRadius: 4,
    //             pointHitRadius: 10,
    //             // notice the gap in the data and the spanGaps: false
    //             data: [10, 20, 60, 95, 64, 78, 90,,70,40,70,89],
    //             spanGaps: false,
    //         }

    //     ]
    // };

    // // Notice the scaleLabel at the same level as Ticks
    // var options = {
    // scales: {
    //             yAxes: [{
    //                 ticks: {
    //                     beginAtZero:true
    //                 },
    //                 scaleLabel: {
    //                     display: true,
    //                     labelString: 'Moola',
    //                     fontSize: 20 
    //                 }
    //             }]            
    //         }  
    // };

    // // Chart declaration:
    // var myBarChart = new Chart(ctx, {
    //     type: 'line',
    //     data: data,
    //     options: options
    // });

    function closeChart() {
        $("#show-device").html('')
    }
</script>

app/views/devices/_devices_rating.html.erb
<table class="table">
    <thead class="thead-dark">
        <tr>
        <th scope="col">#</th>
        <th scope="col">Device ID</th>
        <th scope="col">Power</th>
        <th scope="col">Active</th>
        </tr>
    </thead>
    <tbody id="device-rating-table">
        <% if ratings.present? %>
            <% ratings.each do |rating| %>
                <tr id="device-rating-<%= rating.device_id %>">
                    <th scope="row"><%= rating.id %></th>
                    <td><%= rating.device_id %></td>
                    <td><%= rating.power_consumption %></td>
                    <td><%= rating.is_online %></td>
                </tr>
            <% end %>
        <% else %>
            <div class="alert alert-primary" role="alert">
                No Data Found!
            </div>
        <% end %>
    </tbody>
</table>

app/views/devices/_devices_table.html.erb
<% if devices.present? %>
    <table class="table">
        <thead class="thead-dark">
            <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">UUID</th>
            <th scope="col">User Email</th>
            <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% devices.each do |device| %>
                <tr>
                    <th scope="row"><%= device.id %></th>
                    <td><%= link_to device.name, device_path(device), remote: true %></td>
                    <td><%= device.uuid %></td>
                    <td><%= device.user.email %></td>
                    <td>
                        <%= link_to "Edit", edit_device_path(device), remote: true %> <%= link_to "Delete", device_path(device), method: :delete, data: {confirm: 'Are you sure?'}, remote: true %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% else %>
    <div class="alert alert-primary" role="alert">
        No Data Found!
    </div>
<% end %>

app/views/devices/_form.html.erb
<div class="m-2">
    <%= simple_form_for device, remote: true do |f| %>
        <%= f.input :name %>
        <%= f.input :power_rating %>
        <% if is_admin %>
            <%= f.input :user_id, collection: User.all.pluck(:id) %>
        <% end %>
        <%= f.button :submit, class: 'btn btn-success' %>
        <button type="button" class="btn btn-danger" onclick="removeForm()">Remove Form</button>
    <% end %>
</div>

<script>
    function removeForm() {
        $('#new-device-form-container').html('')
    }
</script>

app/views/devices/create.js.erb
$("#devices-table").html("<%= j render 'devices_table', devices: Device.all %>")
$('#new-device-form-container').html('')

app/views/devices/destroy.js.erb
$("#devices-table").html("<%= j render 'devices_table', devices: Device.all %>")

app/views/devices/edit.js.erb
$("#new-device-form-container").html("<%= j render 'form', device: @device, is_admin: @is_admin %>")

app/views/devices/index.html.erb
<%= link_to "Add New Device", new_device_path, remote: true, class: 'btn btn-primary mt-2 mb-2' %>

<div id="new-device-form-container"></div>

<div id="show-device"></div>

<div id="devices-table" style="overflow: auto">
    <%= render 'devices/devices_table', devices: @devices %>
</div>

<br>

<div id="device-ratings-table">
    <%= render 'devices/devices_rating', ratings: @last_ratings %>
</div>

app/views/devices/new.js.erb
$("#new-device-form-container").html("<%= j render 'form', device: @device, is_admin: @is_admin %>")

app/views/devices/show.js.erb
$("#show-device").html("<%= j render 'device', device: @device, ratings: @ratings %>")

app/views/devices/update.js.erb
$("#devices-table").html("<%= j render 'devices_table', devices: Device.all %>")
$('#new-device-form-container').html('')

app/views/layouts/_flash_message.html.erb
<div class="mt-2">
    <% if notice %>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <%= notice %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>

    <% if alert %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <%= alert %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Elec", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if user_signed_in? %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= 'active' if current_page?(user_panel_index_path) %>">
          <%= link_to "My Dashboard", user_panel_index_path, class: "nav-link" %>
        </li>
        <% if current_user.roles.select { |role| role.name == 'admin' }.present? %>
          <li class="nav-item <%= 'active' if current_page?(show_users_panel_path) %>">
            <%= link_to "Users", show_users_panel_path, class: "nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(show_devices_panel_path) %>">
            <%= link_to "Devices", show_devices_panel_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          Home
        </li>
      </ul>
    <% end %>

    <ul class="navbar-nav justify-content-end">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.email %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Profile</a>
            <a class="dropdown-item" href="#">Settings</a>
            <div class="dropdown-divider"></div>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
      <% else %>
        <li class="nav-item ml-2 mr-2">
          <%= link_to "Log In", new_user_session_path, class: 'btn btn-success nav-link text-white' %>
        </li>
        <li class="nav-item ml-2 mr-2">
          <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary nav-link text-white' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MajorProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash_message' %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Hello, world!</h1>
  <p class="lead">Manage your electrical utilities better with one click.</p>
  <hr class="my-4">
  <p>Sign Up Today</p>
  <p class="lead">
    <%= link_to "Log In", new_user_session_path, class: 'btn btn-success btn-lg' %>
    <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary btn-lg' %>
  </p>
</div>

app/views/user_panel/index.html.erb
<h1>User</h1>